#! /usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"
source "$dir/util.bash"

fetch() {
  git pull --rebase --quiet
}

main() {
  setup "$@"
  fetch
}

main "$@"
