#! /usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"
source "$dir/util.bash"

# expects message text on standard in
new_message() {
  local file
  file="$(userfile)"
  if ! [[ -e "$file" ]] ; then
    # file does not exist: create file
    touch "$file"
  elif ! [[ -s "$file" ]] ; then
    # file is empty: give it content
    out 'a' > "$file"
  else
    # file has content: remove it
    ed -s "$file" <<EOF
g/^/d
wq
EOF
  fi
  git add "$file"
  git commit --quiet -F -
  git push --quiet
}

main() {
  setup "$@"
  new_message
}

main "$@"
