#! /usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"
source "$dir/util.bash"

do_change() {
  local file="$1"
  if ! [[ -e "$file" ]] ; then
    # file does not exist: create file
    touch "$file"
  elif ! [[ -s "$file" ]] ; then
    # file is empty: give it content
    out 'a' > "$file"
  else
    # file has content: remove it
    ed -s "$file" <<EOF
g/^/d
wq
EOF
  fi

}

# expects message text on standard in
new_message() {
  local file
  file="$(userfile)"
  do_change "$file"
  git add "$file"
  git commit --quiet -F -
  git push --quiet &
}

is_not_empty() {
  git log 2>/dev/null 1>&2
}

main() {
  setup "$@"
  if is_not_empty ; then
    # fetch new messages first
    "$dir"/gitchat-fetch "$@"
  fi
  new_message
}

main "$@"
